CREATE TYPE "public"."maya_game_type" AS ENUM('chess', 'sudoku', 'ticTacToe', 'brainteaser', 'math', 'calendar', 'voice', 'ludo', 'snakesLadders', 'connectFour', 'game2048', 'wouldYouRather');--> statement-breakpoint
CREATE TYPE "public"."maya_message_kind" AS ENUM('text', 'voice', 'photo', 'activity');--> statement-breakpoint
CREATE TYPE "public"."maya_message_role" AS ENUM('user', 'maya');--> statement-breakpoint
CREATE TYPE "public"."maya_theme" AS ENUM('violet', 'rose', 'ocean', 'sunset');--> statement-breakpoint
CREATE TYPE "public"."maya_user_role" AS ENUM('user', 'admin');--> statement-breakpoint
CREATE TABLE "maya_daily_checkins" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "maya_daily_checkins_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user_id" integer NOT NULL,
	"check_in_date" varchar(10) NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "maya_game_sessions" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "maya_game_sessions_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user_id" integer NOT NULL,
	"game_type" "maya_game_type" NOT NULL,
	"state" jsonb NOT NULL,
	"result" varchar(32),
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "maya_memories" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "maya_memories_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user_id" integer NOT NULL,
	"topic" varchar(160) NOT NULL,
	"detail" text NOT NULL,
	"category" varchar(48) DEFAULT 'preference' NOT NULL,
	"relevance" integer DEFAULT 3 NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "maya_messages" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "maya_messages_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user_id" integer NOT NULL,
	"role" "maya_message_role" NOT NULL,
	"kind" "maya_message_kind" DEFAULT 'text' NOT NULL,
	"content" text NOT NULL,
	"media_url" text,
	"emotion" varchar(32),
	"emotion_intensity" integer,
	"reactions" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "maya_mood_logs" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "maya_mood_logs_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user_id" integer NOT NULL,
	"check_in_id" integer,
	"user_mood" varchar(96) NOT NULL,
	"maya_emotion" varchar(32) NOT NULL,
	"intensity" integer NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "maya_preferences" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "maya_preferences_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user_id" integer NOT NULL,
	"theme" "maya_theme" DEFAULT 'violet' NOT NULL,
	"voice_style" integer DEFAULT 0 NOT NULL,
	"display_photo" text,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "maya_relationships" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "maya_relationships_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user_id" integer NOT NULL,
	"rapport_score" integer DEFAULT 1 NOT NULL,
	"preferred_tone" varchar(64) DEFAULT 'warm and curious' NOT NULL,
	"recurring_mood" varchar(96),
	"last_meaningful_topic" varchar(160),
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "maya_youtube_sessions" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "maya_youtube_sessions_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user_id" integer NOT NULL,
	"video_url" text NOT NULL,
	"title" varchar(320),
	"notes" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "users" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "users_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"open_id" varchar(64) NOT NULL,
	"name" text,
	"email" varchar(320),
	"login_method" varchar(64),
	"role" "maya_user_role" DEFAULT 'user' NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"last_signed_in" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "users_open_id_unique" UNIQUE("open_id")
);
--> statement-breakpoint
ALTER TABLE "maya_daily_checkins" ADD CONSTRAINT "maya_daily_checkins_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "maya_game_sessions" ADD CONSTRAINT "maya_game_sessions_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "maya_memories" ADD CONSTRAINT "maya_memories_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "maya_messages" ADD CONSTRAINT "maya_messages_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "maya_mood_logs" ADD CONSTRAINT "maya_mood_logs_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "maya_mood_logs" ADD CONSTRAINT "maya_mood_logs_check_in_id_maya_daily_checkins_id_fk" FOREIGN KEY ("check_in_id") REFERENCES "public"."maya_daily_checkins"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "maya_preferences" ADD CONSTRAINT "maya_preferences_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "maya_relationships" ADD CONSTRAINT "maya_relationships_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "maya_youtube_sessions" ADD CONSTRAINT "maya_youtube_sessions_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "maya_daily_checkins_user_date_unique" ON "maya_daily_checkins" USING btree ("user_id","check_in_date");--> statement-breakpoint
CREATE INDEX "maya_daily_checkins_user_created_idx" ON "maya_daily_checkins" USING btree ("user_id","created_at");--> statement-breakpoint
CREATE INDEX "maya_games_user_updated_idx" ON "maya_game_sessions" USING btree ("user_id","updated_at");--> statement-breakpoint
CREATE INDEX "maya_memories_user_updated_idx" ON "maya_memories" USING btree ("user_id","updated_at");--> statement-breakpoint
CREATE INDEX "maya_messages_user_created_idx" ON "maya_messages" USING btree ("user_id","created_at");--> statement-breakpoint
CREATE INDEX "maya_mood_user_created_idx" ON "maya_mood_logs" USING btree ("user_id","created_at");--> statement-breakpoint
CREATE INDEX "maya_mood_session_created_idx" ON "maya_mood_logs" USING btree ("user_id","check_in_id","created_at");--> statement-breakpoint
CREATE UNIQUE INDEX "maya_preferences_user_unique" ON "maya_preferences" USING btree ("user_id");--> statement-breakpoint
CREATE UNIQUE INDEX "maya_relationships_user_unique" ON "maya_relationships" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "maya_youtube_user_created_idx" ON "maya_youtube_sessions" USING btree ("user_id","created_at");
--> statement-breakpoint
REVOKE ALL ON ALL TABLES IN SCHEMA public FROM anon, authenticated;--> statement-breakpoint
REVOKE ALL ON ALL SEQUENCES IN SCHEMA public FROM anon, authenticated;--> statement-breakpoint
GRANT USAGE ON SCHEMA public TO service_role;--> statement-breakpoint
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO service_role;--> statement-breakpoint
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO service_role;--> statement-breakpoint
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE public.maya_messages ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE public.maya_memories ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE public.maya_daily_checkins ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE public.maya_mood_logs ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE public.maya_preferences ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE public.maya_relationships ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE public.maya_game_sessions ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE public.maya_youtube_sessions ENABLE ROW LEVEL SECURITY;
